/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameMateriasAprobadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameMateriasAprobadas
     */
    public FrameMateriasAprobadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenu();
        ItemMaterias = new javax.swing.JMenu();
        itemAsistencias = new javax.swing.JMenu();
        ItemsCalificacion = new javax.swing.JMenu();
        ItemsAcademicos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ItemsSalir = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Materias Aprobadas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Materia", "Calificacion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnVolver.setText("Volver al Inicio");

        jMenuBar1.setBackground(new java.awt.Color(27, 58, 107));

        jMenu1.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu1.add(ItemPerfil);

        ItemMaterias.setText("Gestion De Materias");
        jMenu1.add(ItemMaterias);

        itemAsistencias.setText("Registrar Asistencia ");
        jMenu1.add(itemAsistencias);

        ItemsCalificacion.setText("Registrar Calificacion ");
        ItemsCalificacion.setToolTipText("");
        jMenu1.add(ItemsCalificacion);

        ItemsAcademicos.setText("Reportes Academicos");

        jMenu2.setText("Situacion General");
        ItemsAcademicos.add(jMenu2);

        jMenu3.setText("Materias en Riesgo");
        ItemsAcademicos.add(jMenu3);

        jMenu4.setText("Materias Aprobadas");
        ItemsAcademicos.add(jMenu4);

        jMenu1.add(ItemsAcademicos);

        ItemsSalir.setText("Salir");
        jMenu1.add(ItemsSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnVolver)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnVolver)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ItemMaterias;
    private javax.swing.JMenu ItemPerfil;
    private javax.swing.JMenu ItemsAcademicos;
    private javax.swing.JMenu ItemsCalificacion;
    private javax.swing.JMenu ItemsSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenu itemAsistencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
