/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameRegistrarCalificacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameRegistrarCalificacion
     */
    public FrameRegistrarCalificacion() {
        initComponents();
        setBackground(new java.awt.Color(200, 216, 240));
        getContentPane().setBackground(new java.awt.Color(200, 216, 240));
        cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbMaterias = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        NotasCargadasEN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nota = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenuItem();
        ItemAsistencia = new javax.swing.JMenuItem();
        ItemGestionM = new javax.swing.JMenuItem();
        ItemCalificacion = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        ItemSitGeneral = new javax.swing.JMenuItem();
        ItemMatRiesgo = new javax.swing.JMenuItem();
        ItemMatAprobadas = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione una Materia: ");

        cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematica (MAT)", "Programacion (PRO)", "Base De Datos (BDD)" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nota del 0 - 10 / max 5 por materia");

        NotasCargadasEN.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Notas Cargadas en ---");

        Nota.addActionListener(this::NotaActionPerformed);

        btnRegistrar.setBackground(new java.awt.Color(107, 79, 163));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar Nota");
        btnRegistrar.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(107, 79, 163));
        jLabel8.setText("Registrar Calificacion");

        btnVolver.setText("Volver al inicio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nota)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(btnRegistrar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(btnVolver))
                                            .addComponent(NotasCargadasEN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nota, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(NotasCargadasEN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVolver)))
        );

        jMenuBar2.setBackground(new java.awt.Color(200, 216, 240));

        jMenu10.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu10.add(ItemPerfil);

        ItemAsistencia.setText("Registrar Asistencia");
        jMenu10.add(ItemAsistencia);

        ItemGestionM.setText("Gestion de Materias");
        jMenu10.add(ItemGestionM);

        ItemCalificacion.setText("Registrar Calificacion");
        jMenu10.add(ItemCalificacion);

        Reportes.setText("Reportes Academicos");

        ItemSitGeneral.setText("Situacion General");
        Reportes.add(ItemSitGeneral);

        ItemMatRiesgo.setText("Materias en Riesgo");
        Reportes.add(ItemMatRiesgo);

        ItemMatAprobadas.setText("Materias Aprobadas");
        Reportes.add(ItemMatAprobadas);

        jMenu10.add(Reportes);

        ItemSalir.setText("Salir");
        jMenu10.add(ItemSalir);

        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaActionPerformed
private controlador.Controlador controlador;

public FrameRegistrarCalificacion(controlador.Controlador controlador) {
    initComponents();
    this.controlador = controlador;
    setBackground(new java.awt.Color(200, 216, 240));
    getContentPane().setBackground(new java.awt.Color(200, 216, 240));
    cargarComboMaterias();

    btnRegistrar.addActionListener(e -> {
        if (cmbMaterias.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay materias inscriptas.");
            return;
        }
        try {
            String item = cmbMaterias.getSelectedItem().toString();
            String codigo = item.substring(item.indexOf('(')+1, item.indexOf(')'));
            double nota = Double.parseDouble(Nota.getText().trim());
            controlador.registrarNota(codigo, nota);
            modelo.InscripcionMateria insc = controlador.buscarMateria(codigo);
            if (insc != null) {
                NotasCargadasEN.setText(insc.getNotas().toString()
                    + "  Prom: " + String.format("%.2f", insc.getNota()));
                Nota.setText("");
            }
        } catch (IllegalStateException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresá un número entre 0 y 10.");
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    });

    ItemPerfil.addActionListener(e -> abrirFrame(new FramePerfil(controlador), 550, 420, 100, 50));
    ItemGestionM.addActionListener(e -> abrirFrame(new FrameGestionMaterias(controlador), 900, 550, 50, 30));
    ItemAsistencia.addActionListener(e -> abrirFrame(new FrameAsistencias(controlador), 650, 400, 150, 80));
    ItemSitGeneral.addActionListener(e -> abrirFrame(new frameSituacionGeneral(controlador), 750, 500, 100, 50));
    ItemMatRiesgo.addActionListener(e -> abrirFrame(new FrameMateriasEnRiesgo(controlador), 550, 400, 150, 80));
    ItemMatAprobadas.addActionListener(e -> abrirFrame(new FrameMateriasAprobadas(controlador), 550, 400, 150, 80));
    ItemSalir.addActionListener(e -> System.exit(0));
     btnVolver.addActionListener(e -> {
    FrameBienvenida f = new FrameBienvenida(controlador);
    f.pack();
    f.setLocation(
        (this.getDesktopPane().getWidth() - f.getWidth()) / 2,
        (this.getDesktopPane().getHeight() - f.getHeight()) / 2
    );
    this.getDesktopPane().add(f);
    f.setVisible(true);
    this.dispose();
});
}

private void cargarComboMaterias() {
    cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>());
    for (modelo.InscripcionMateria i : controlador.getEstudiante().getMaterias())
        cmbMaterias.addItem(i.getMateria().getNombre()
            + " (" + i.getMateria().getCodigo() + ")");
}

private void abrirFrame(javax.swing.JInternalFrame frame, int w, int h, int x, int y) {
    frame.pack();
    frame.setLocation(
        (this.getDesktopPane().getWidth() - frame.getWidth()) / 2,
        (this.getDesktopPane().getHeight() - frame.getHeight()) / 2
    );
    this.getDesktopPane().add(frame);
    frame.setVisible(true);
    this.dispose();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAsistencia;
    private javax.swing.JMenuItem ItemCalificacion;
    private javax.swing.JMenuItem ItemGestionM;
    private javax.swing.JMenuItem ItemMatAprobadas;
    private javax.swing.JMenuItem ItemMatRiesgo;
    private javax.swing.JMenuItem ItemPerfil;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem ItemSitGeneral;
    private javax.swing.JTextField Nota;
    private javax.swing.JLabel NotasCargadasEN;
    private javax.swing.JMenu Reportes;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
