/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameMateriasAprobadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameMateriasAprobadas
     */
    public FrameMateriasAprobadas() {
        initComponents();
        setBackground(new java.awt.Color(200, 216, 240));
        getContentPane().setBackground(new java.awt.Color(200, 216, 240));
        jTable1.setBackground(new java.awt.Color(46, 80, 140));
        jTable1.setForeground(java.awt.Color.WHITE);
        jTable1.setSelectionBackground(new java.awt.Color(107, 79, 163));
        jTable1.getTableHeader().setBackground(new java.awt.Color(27, 58, 107));
        jTable1.getTableHeader().setForeground(java.awt.Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenuItem();
        ItemAsistencia = new javax.swing.JMenuItem();
        ItemGestionM = new javax.swing.JMenuItem();
        ItemCalificacion = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        ItemSitGeneral = new javax.swing.JMenuItem();
        ItemMatRiesgo = new javax.swing.JMenuItem();
        ItemMatAprobadas = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Materias Aprobadas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Materia", "Calificacion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnVolver.setBackground(new java.awt.Color(107, 79, 163));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver al Inicio");

        jMenuBar2.setBackground(new java.awt.Color(200, 216, 240));

        jMenu10.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu10.add(ItemPerfil);

        ItemAsistencia.setText("Registrar Asistencia");
        jMenu10.add(ItemAsistencia);

        ItemGestionM.setText("Gestion de Materias");
        jMenu10.add(ItemGestionM);

        ItemCalificacion.setText("Registrar Calificacion");
        jMenu10.add(ItemCalificacion);

        Reportes.setText("Reportes Academicos");

        ItemSitGeneral.setText("Situacion General");
        Reportes.add(ItemSitGeneral);

        ItemMatRiesgo.setText("Materias en Riesgo");
        Reportes.add(ItemMatRiesgo);

        ItemMatAprobadas.setText("Materias Aprobadas");
        Reportes.add(ItemMatAprobadas);

        jMenu10.add(Reportes);

        ItemSalir.setText("Salir");
        jMenu10.add(ItemSalir);

        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnVolver)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnVolver)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAsistencia;
    private javax.swing.JMenuItem ItemCalificacion;
    private javax.swing.JMenuItem ItemGestionM;
    private javax.swing.JMenuItem ItemMatAprobadas;
    private javax.swing.JMenuItem ItemMatRiesgo;
    private javax.swing.JMenuItem ItemPerfil;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem ItemSitGeneral;
    private javax.swing.JMenu Reportes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
