/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class frameSituacionGeneral extends javax.swing.JInternalFrame {

    /**
     * Creates new form frameSituacionGeneral
     */
    public frameSituacionGeneral() {
        initComponents();
        setBackground(new java.awt.Color(200, 216, 240));
        getContentPane().setBackground(new java.awt.Color(200, 216, 240));

        // Colores de la tabla
        TablaMaterias.setBackground(new java.awt.Color(46, 80, 140));
        TablaMaterias.setSelectionBackground(new java.awt.Color(107, 79, 163));
        TablaMaterias.getTableHeader().setBackground(new java.awt.Color(27, 58, 107));
        TablaMaterias.getTableHeader().setForeground(java.awt.Color.WHITE);

    }
    
        private controlador.Controlador controlador;

     public frameSituacionGeneral(controlador.Controlador controlador) {
         initComponents();
         this.controlador = controlador;
         setBackground(new java.awt.Color(200, 216, 240));
         getContentPane().setBackground(new java.awt.Color(200, 216, 240));
         TablaMaterias.setBackground(new java.awt.Color(46, 80, 140));
         TablaMaterias.setSelectionBackground(new java.awt.Color(107, 79, 163));
         TablaMaterias.getTableHeader().setBackground(new java.awt.Color(27, 58, 107));
         TablaMaterias.getTableHeader().setForeground(java.awt.Color.WHITE);

         getNombreAlumno().setText(controlador.getEstudiante().getNombre());
         getPromedioGeneral().setText(String.format("%.2f", controlador.getEstudiante().getPromedioGeneral()));

         javax.swing.table.DefaultTableModel m =
             (javax.swing.table.DefaultTableModel) getTablaMaterias().getModel();
         m.setRowCount(0);
         for (modelo.InscripcionMateria i : controlador.getEstudiante().getMaterias()) {
             m.addRow(new Object[]{
                 i.getMateria().getNombre(), i.getMateria().getCodigo(),
                 i.getMateria().getCuatrimestre(), i.getMateria().getAnio(),
                 i.getCondicion(),
                 String.format("%.1f%%", i.getPorcentajeAsistencia()),
                 String.format("%.2f", i.getNota())
             });
            
             TablaMaterias.getColumnModel().getColumn(0).setPreferredWidth(120); // Nombre
            TablaMaterias.getColumnModel().getColumn(1).setPreferredWidth(60);  // Codigo
            TablaMaterias.getColumnModel().getColumn(2).setPreferredWidth(80);  // Cuatrimestre
            TablaMaterias.getColumnModel().getColumn(3).setPreferredWidth(50);  // Año
            TablaMaterias.getColumnModel().getColumn(4).setPreferredWidth(70);  // Condicion
            TablaMaterias.getColumnModel().getColumn(5).setPreferredWidth(80);  // Asistencia
            TablaMaterias.getColumnModel().getColumn(6).setPreferredWidth(70);  // Promedio
            TablaMaterias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
         }

         ItemPerfil.addActionListener(e -> abrirFrame(new FramePerfil(controlador), 550, 420, 100, 50));
         ItemGestionM.addActionListener(e -> abrirFrame(new FrameGestionMaterias(controlador), 900, 550, 50, 30));
         ItemAsistencia.addActionListener(e -> abrirFrame(new FrameAsistencias(controlador), 650, 400, 150, 80));
         ItemCalificacion.addActionListener(e -> abrirFrame(new FrameRegistrarCalificacion(controlador), 650, 400, 150, 80));
         ItemMatRiesgo.addActionListener(e -> abrirFrame(new FrameMateriasEnRiesgo(controlador), 550, 400, 150, 80));
         ItemMatAprobadas.addActionListener(e -> abrirFrame(new FrameMateriasAprobadas(controlador), 550, 400, 150, 80));
         ItemSalir.addActionListener(e -> System.exit(0));
         btnVolver.addActionListener(e -> {
        FrameBienvenida f = new FrameBienvenida(controlador);
        f.setSize(500, 300);
        f.setLocation(300, 200);
        this.getDesktopPane().add(f);
        f.setVisible(true);
        this.dispose();
});
     }

     private void abrirFrame(javax.swing.JInternalFrame frame, int w, int h, int x, int y) {
         frame.setSize(w, h); frame.setLocation(x, y);
         this.getDesktopPane().add(frame);
         frame.setVisible(true); this.dispose();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreAlumno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        PromedioGeneral = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenuItem();
        ItemAsistencia = new javax.swing.JMenuItem();
        ItemGestionM = new javax.swing.JMenuItem();
        ItemCalificacion = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        ItemSitGen = new javax.swing.JMenuItem();
        ItemMatRiesgo = new javax.swing.JMenuItem();
        ItemMatAprobadas = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 79, 163));
        jLabel1.setText("Situacion General ");

        NombreAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TablaMaterias.setBorder(javax.swing.BorderFactory.createTitledBorder("Materias Inscriptas"));
        TablaMaterias.setForeground(new java.awt.Color(255, 255, 255));
        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Cuatrimetre", "Año", "Condicion", "Asistencia", "Promedio"
            }
        ));
        TablaMaterias.setToolTipText("");
        jScrollPane1.setViewportView(TablaMaterias);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Promedio General: ");

        btnVolver.setBackground(new java.awt.Color(107, 79, 163));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver al Inicio");

        jMenuBar2.setBackground(new java.awt.Color(200, 216, 240));

        jMenu.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu.add(ItemPerfil);

        ItemAsistencia.setText("Registrar Asistencia");
        jMenu.add(ItemAsistencia);

        ItemGestionM.setText("Gestion de Materias");
        jMenu.add(ItemGestionM);

        ItemCalificacion.setText("Registrar Calificacion");
        jMenu.add(ItemCalificacion);

        MenuReportes.setText("Reportes Academicos");

        ItemSitGen.setText("Situacion General");
        MenuReportes.add(ItemSitGen);

        ItemMatRiesgo.setText("Materias en Riesgo");
        MenuReportes.add(ItemMatRiesgo);

        ItemMatAprobadas.setText("Materias Aprobadas");
        MenuReportes.add(ItemMatAprobadas);

        jMenu.add(MenuReportes);

        ItemSalir.setText("Salir");
        jMenu.add(ItemSalir);

        jMenuBar2.add(jMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(82, 82, 82))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(PromedioGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVolver)
                            .addGap(136, 136, 136)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NombreAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(319, 319, 319))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(NombreAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnVolver)
                    .addComponent(PromedioGeneral))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAsistencia;
    private javax.swing.JMenuItem ItemCalificacion;
    private javax.swing.JMenuItem ItemGestionM;
    private javax.swing.JMenuItem ItemMatAprobadas;
    private javax.swing.JMenuItem ItemMatRiesgo;
    private javax.swing.JMenuItem ItemPerfil;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem ItemSitGen;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JLabel NombreAlumno;
    private javax.swing.JLabel PromedioGeneral;
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
public javax.swing.JLabel getNombreAlumno() { return NombreAlumno; }
public javax.swing.JTable getTablaMaterias() { return TablaMaterias; }
public javax.swing.JLabel getPromedioGeneral() { return PromedioGeneral; }

}
