/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameMateriasEnRiesgo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameMateriasEnRiesgo
     */
    public FrameMateriasEnRiesgo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenu();
        ItemMaterias = new javax.swing.JMenu();
        itemAsistencias = new javax.swing.JMenu();
        ItemsCalificacion = new javax.swing.JMenu();
        ItemsAcademicos = new javax.swing.JMenu();
        ItemsSalir = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Materias en Riesgo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Asistencias entre el 75% y 85%");

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVolver.setText("Volver al inicio ");

        jMenuBar1.setBackground(new java.awt.Color(27, 58, 107));

        jMenu1.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu1.add(ItemPerfil);

        ItemMaterias.setText("Gestion De Materias");
        jMenu1.add(ItemMaterias);

        itemAsistencias.setText("Registrar Asistencia ");
        jMenu1.add(itemAsistencias);

        ItemsCalificacion.setText("Registrar Calificacion ");
        ItemsCalificacion.setToolTipText("");
        jMenu1.add(ItemsCalificacion);

        ItemsAcademicos.setText("Reportes Academicos");
        jMenu1.add(ItemsAcademicos);

        ItemsSalir.setText("Salir");
        jMenu1.add(ItemsSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnVolver)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnVolver)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ItemMaterias;
    private javax.swing.JMenu ItemPerfil;
    private javax.swing.JMenu ItemsAcademicos;
    private javax.swing.JMenu ItemsCalificacion;
    private javax.swing.JMenu ItemsSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenu itemAsistencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
