/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameBienvenida extends javax.swing.JInternalFrame {
      /**
     * Creates new form FrameBienvenida
     */
    public FrameBienvenida() {
        initComponents();
        setBackground(new java.awt.Color(200, 216, 240));
        getContentPane().setBackground(new java.awt.Color(200, 216, 240));
        
    }
    private controlador.Controlador controlador;

public FrameBienvenida(controlador.Controlador controlador) {
    initComponents();
    this.controlador = controlador;
    setBackground(new java.awt.Color(200, 216, 240));
    getContentPane().setBackground(new java.awt.Color(200, 216, 240));
    btnIngresar.addActionListener(e -> {
        FramePerfil f = new FramePerfil(controlador);
        f.setSize(550, 420);
        f.setLocation(100, 50);
        this.getDesktopPane().add(f);
        f.setVisible(true);
        this.dispose();
    });
}
private void abrirFrame(javax.swing.JInternalFrame frame, int w, int h, int x, int y) {
    frame.pack();
    frame.setLocation(
        (this.getDesktopPane().getWidth() - frame.getWidth()) / 2,
        (this.getDesktopPane().getHeight() - frame.getHeight()) / 2
    );
    this.getDesktopPane().add(frame);
    frame.setVisible(true);
    this.dispose();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(200, 216, 240));
        setTitle("Sistema de Autogestion");

        lblTitulo.setBackground(new java.awt.Color(200, 216, 240));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Sistema De Autogestion");

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblSubtitulo.setText("Gestion Academica de Estudiantes");

        btnIngresar.setBackground(new java.awt.Color(107, 79, 163));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblSubtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnIngresar)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblSubtitulo)
                .addGap(48, 48, 48)
                .addComponent(btnIngresar)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
