/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameMateriasAprobadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameMateriasAprobadas
     */
    public FrameMateriasAprobadas() {
        initComponents();
        setBackground(new java.awt.Color(200, 216, 240));
        getContentPane().setBackground(new java.awt.Color(200, 216, 240));
        jTable1.setBackground(new java.awt.Color(46, 80, 140));
        jTable1.setForeground(java.awt.Color.WHITE);
        jTable1.setSelectionBackground(new java.awt.Color(107, 79, 163));
        jTable1.getTableHeader().setBackground(new java.awt.Color(27, 58, 107));
        jTable1.getTableHeader().setForeground(java.awt.Color.WHITE);

    }
    
    private controlador.Controlador controlador;

    public FrameMateriasAprobadas(controlador.Controlador controlador) {
    initComponents();
    this.controlador = controlador;
    setBackground(new java.awt.Color(200, 216, 240));
    getContentPane().setBackground(new java.awt.Color(200, 216, 240));
    jTable1.setBackground(new java.awt.Color(46, 80, 140));
    jTable1.setForeground(java.awt.Color.WHITE);
    jTable1.setSelectionBackground(new java.awt.Color(107, 79, 163));
    jTable1.getTableHeader().setBackground(new java.awt.Color(27, 58, 107));
    jTable1.getTableHeader().setForeground(java.awt.Color.WHITE);

    javax.swing.table.DefaultTableModel m =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    m.setRowCount(0);
    for (modelo.InscripcionMateria i : controlador.getEstudiante().getMateriasAprobadas()) {
        m.addRow(new Object[]{
            i.getMateria().getNombre(),
            String.format("%.2f", i.getNota())
        });
    }
    jTable1.revalidate();
    jTable1.repaint();
    javax.swing.JLabel lblEstadisticas = new javax.swing.JLabel();
    lblEstadisticas.setFont(new java.awt.Font("Segoe UI", 0, 13));
    lblEstadisticas.setForeground(new java.awt.Color(107, 79, 163));
    getContentPane().add(lblEstadisticas);
    if (m.getRowCount() > 0) {
    double max = 0, min = 10, suma = 0;
    for (int i = 0; i < m.getRowCount(); i++) {
        double nota = Double.parseDouble(m.getValueAt(i, 1).toString());
        if (nota > max) max = nota;
        if (nota < min) min = nota;
        suma += nota;
    }
    lblEstadisticas.setText("Máx: " + String.format("%.2f", max)
    + "  Min: " + String.format("%.2f", min)
    + "  Prom: " + String.format("%.2f", suma / m.getRowCount())
    + "  Total: " + m.getRowCount());
}
    if (m.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "No hay materias aprobadas aún.\n(Se requiere condición Regular y nota ≥ 6)",
            "Sin resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    ItemPerfil.addActionListener(e -> abrirFrame(new FramePerfil(controlador), 550, 420, 100, 50));
    ItemGestionM.addActionListener(e -> abrirFrame(new FrameGestionMaterias(controlador), 900, 550, 50, 30));
    ItemAsistencia.addActionListener(e -> abrirFrame(new FrameAsistencias(controlador), 650, 400, 150, 80));
    ItemCalificacion.addActionListener(e -> abrirFrame(new FrameRegistrarCalificacion(controlador), 650, 400, 150, 80));
    ItemSitGeneral.addActionListener(e -> abrirFrame(new frameSituacionGeneral(controlador), 750, 500, 100, 50));
    ItemMatRiesgo.addActionListener(e -> abrirFrame(new FrameMateriasEnRiesgo(controlador), 550, 400, 150, 80));
    ItemSalir.addActionListener(e -> System.exit(0));
    btnVolver.addActionListener(e -> {
    FrameBienvenida f = new FrameBienvenida(controlador);
    f.setSize(500, 300);
    f.setLocation(300, 200);
    this.getDesktopPane().add(f);
    f.setVisible(true);
    this.dispose();
});
}

    private void abrirFrame(javax.swing.JInternalFrame frame, int w, int h, int x, int y) {
    frame.setSize(w, h); frame.setLocation(x, y);
    this.getDesktopPane().add(frame);
    frame.setVisible(true); this.dispose();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenuItem();
        ItemAsistencia = new javax.swing.JMenuItem();
        ItemGestionM = new javax.swing.JMenuItem();
        ItemCalificacion = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        ItemSitGeneral = new javax.swing.JMenuItem();
        ItemMatRiesgo = new javax.swing.JMenuItem();
        ItemMatAprobadas = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Materia", "Calificacion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnVolver.setBackground(new java.awt.Color(107, 79, 163));
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver al Inicio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 79, 163));
        jLabel2.setText("Materias Aprobadas");

        jMenuBar2.setBackground(new java.awt.Color(200, 216, 240));

        jMenu10.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu10.add(ItemPerfil);

        ItemAsistencia.setText("Registrar Asistencia");
        jMenu10.add(ItemAsistencia);

        ItemGestionM.setText("Gestion de Materias");
        jMenu10.add(ItemGestionM);

        ItemCalificacion.setText("Registrar Calificacion");
        jMenu10.add(ItemCalificacion);

        Reportes.setText("Reportes Academicos");

        ItemSitGeneral.setText("Situacion General");
        Reportes.add(ItemSitGeneral);

        ItemMatRiesgo.setText("Materias en Riesgo");
        Reportes.add(ItemMatRiesgo);

        ItemMatAprobadas.setText("Materias Aprobadas");
        Reportes.add(ItemMatAprobadas);

        jMenu10.add(Reportes);

        ItemSalir.setText("Salir");
        jMenu10.add(ItemSalir);

        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnVolver)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAsistencia;
    private javax.swing.JMenuItem ItemCalificacion;
    private javax.swing.JMenuItem ItemGestionM;
    private javax.swing.JMenuItem ItemMatAprobadas;
    private javax.swing.JMenuItem ItemMatRiesgo;
    private javax.swing.JMenuItem ItemPerfil;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem ItemSitGeneral;
    private javax.swing.JMenu Reportes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
