/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameAsistencias extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameAsistencias
     */
    public FrameAsistencias() {
        initComponents();
        setBackground(new java.awt.Color(200, 216, 240));
        getContentPane().setBackground(new java.awt.Color(200, 216, 240));
        javax.swing.ButtonGroup grupoAsistencia = new javax.swing.ButtonGroup();
        grupoAsistencia.add(rdbPresente);
        grupoAsistencia.add(rdbAusente);
        rdbPresente.setSelected(true); // por defecto: Presente seleccionado
        cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>());


    }
    private controlador.Controlador controlador;

public FrameAsistencias(controlador.Controlador controlador) {
    initComponents();
    this.controlador = controlador;
    setBackground(new java.awt.Color(200, 216, 240));
    getContentPane().setBackground(new java.awt.Color(200, 216, 240));
    javax.swing.ButtonGroup grupoAsistencia = new javax.swing.ButtonGroup();
    grupoAsistencia.add(rdbPresente);
    grupoAsistencia.add(rdbAusente);
    rdbPresente.setSelected(true);
    cargarComboMaterias();

    btnResgistrar.addActionListener(e -> {
        if (cmbMaterias.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay materias inscriptas.");
            return;
        }
        String item = cmbMaterias.getSelectedItem().toString();
        String codigo = item.substring(item.indexOf('(')+1, item.indexOf(')'));
        controlador.registrarAsistencia(codigo, rdbPresente.isSelected());
        modelo.InscripcionMateria insc = controlador.buscarMateria(codigo);
        if (insc != null) {
            double porc = insc.getPorcentajeAsistencia();
            lblEstadoAsistencia.setText(insc.getMateria().getNombre()
                + ": " + String.format("%.1f%%", porc));
                Estado.setText(insc.getCondicion());
            if (porc < 75)
                javax.swing.JOptionPane.showMessageDialog(this,
                    "⚠ '" + insc.getMateria().getNombre() + "' bajó al "
                    + String.format("%.1f%%", porc) + ".\nEl alumno quedó LIBRE.",
                    "Alerta de Asistencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    });

    ItemPerfil.addActionListener(e -> abrirFrame(new FramePerfil(controlador), 550, 420, 100, 50));
    ItemGestionM.addActionListener(e -> abrirFrame(new FrameGestionMaterias(controlador), 900, 550, 50, 30));
    ItemCalificacion.addActionListener(e -> abrirFrame(new FrameRegistrarCalificacion(controlador), 650, 400, 150, 80));
    ItemSitGeneral.addActionListener(e -> abrirFrame(new frameSituacionGeneral(controlador), 750, 500, 100, 50));
    ItemMatRiesgo.addActionListener(e -> abrirFrame(new FrameMateriasEnRiesgo(controlador), 550, 400, 150, 80));
    ItemMatAprobadas.addActionListener(e -> abrirFrame(new FrameMateriasAprobadas(controlador), 550, 400, 150, 80));
    ItemSalir.addActionListener(e -> System.exit(0));
    btnVolver.addActionListener(e -> {
    FrameBienvenida f = new FrameBienvenida(controlador);
    f.pack();
    f.setLocation(
        (this.getDesktopPane().getWidth() - f.getWidth()) / 2,
        (this.getDesktopPane().getHeight() - f.getHeight()) / 2
    );
    this.getDesktopPane().add(f);
    f.setVisible(true);
    this.dispose();
});
    
}

    private void cargarComboMaterias() {
        cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>());
        for (modelo.InscripcionMateria i : controlador.getEstudiante().getMaterias())
            cmbMaterias.addItem(i.getMateria().getNombre()
                + " (" + i.getMateria().getCodigo() + ")");
    }

   private void abrirFrame(javax.swing.JInternalFrame frame, int w, int h, int x, int y) {
    frame.pack();
    frame.setLocation(
        (this.getDesktopPane().getWidth() - frame.getWidth()) / 2,
        (this.getDesktopPane().getHeight() - frame.getHeight()) / 2
    );
    this.getDesktopPane().add(frame);
    frame.setVisible(true);
    this.dispose();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbMaterias = new javax.swing.JComboBox<>();
        lblEstadoAsistencia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdbPresente = new javax.swing.JRadioButton();
        rdbAusente = new javax.swing.JRadioButton();
        lblEstadoAsistencia1 = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        SituacionActual1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnResgistrar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenuItem();
        ItemAsistencia = new javax.swing.JMenuItem();
        ItemGestionM = new javax.swing.JMenuItem();
        ItemCalificacion = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        ItemSitGeneral = new javax.swing.JMenuItem();
        ItemMatRiesgo = new javax.swing.JMenuItem();
        ItemMatAprobadas = new javax.swing.JMenuItem();
        ItemSalir = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione una Materia:");

        cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematica (MAT)", "Programacion (PRO)", "Base De Datos (BDD)" }));

        lblEstadoAsistencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoAsistencia.setText("Asistencia actual:  ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("¿Estuvo Presente?");

        rdbPresente.setText("Presente");

        rdbAusente.setText("Ausente");

        lblEstadoAsistencia1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoAsistencia1.setText("Estado:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 79, 163));
        jLabel2.setText("Cargar Asistencia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(234, 234, 234))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbPresente)
                                    .addComponent(lblEstadoAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SituacionActual1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdbAusente)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(16, 16, 16)))))
                .addGap(16, 16, 16)
                .addComponent(lblEstadoAsistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbPresente)
                    .addComponent(rdbAusente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstadoAsistencia1)
                    .addComponent(lblEstadoAsistencia)
                    .addComponent(SituacionActual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        btnVolver.setText("Volver al Inicio");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        btnResgistrar.setBackground(new java.awt.Color(107, 79, 163));
        btnResgistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnResgistrar.setText("Registrar Asistencia");

        jMenuBar2.setBackground(new java.awt.Color(200, 216, 240));

        jMenu10.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu10.add(ItemPerfil);

        ItemAsistencia.setText("Registrar Asistencia");
        jMenu10.add(ItemAsistencia);

        ItemGestionM.setText("Gestion de Materias");
        jMenu10.add(ItemGestionM);

        ItemCalificacion.setText("Registrar Calificacion");
        jMenu10.add(ItemCalificacion);

        Reportes.setText("Reportes Academicos");

        ItemSitGeneral.setText("Situacion General");
        Reportes.add(ItemSitGeneral);

        ItemMatRiesgo.setText("Materias en Riesgo");
        Reportes.add(ItemMatRiesgo);

        ItemMatAprobadas.setText("Materias Aprobadas");
        Reportes.add(ItemMatAprobadas);

        jMenu10.add(Reportes);

        ItemSalir.setText("Salir");
        jMenu10.add(ItemSalir);

        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResgistrar)
                .addGap(44, 44, 44)
                .addComponent(btnVolver)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnResgistrar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estado;
    private javax.swing.JMenuItem ItemAsistencia;
    private javax.swing.JMenuItem ItemCalificacion;
    private javax.swing.JMenuItem ItemGestionM;
    private javax.swing.JMenuItem ItemMatAprobadas;
    private javax.swing.JMenuItem ItemMatRiesgo;
    private javax.swing.JMenuItem ItemPerfil;
    private javax.swing.JMenuItem ItemSalir;
    private javax.swing.JMenuItem ItemSitGeneral;
    private javax.swing.JMenu Reportes;
    private javax.swing.JLabel SituacionActual1;
    private javax.swing.JButton btnResgistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoAsistencia;
    private javax.swing.JLabel lblEstadoAsistencia1;
    private javax.swing.JRadioButton rdbAusente;
    private javax.swing.JRadioButton rdbPresente;
    // End of variables declaration//GEN-END:variables
}
