/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author laram
 */
public class FrameGestionMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameGestionMaterias
     */
    public FrameGestionMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Alertas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        btnBaja = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Panelinscribir = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemPerfil = new javax.swing.JMenu();
        ItemMaterias = new javax.swing.JMenu();
        itemAsistencias = new javax.swing.JMenu();
        ItemsCalificacion = new javax.swing.JMenu();
        ItemsAcademicos = new javax.swing.JMenu();
        ItemsSalir = new javax.swing.JMenu();

        Alertas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(Alertas);

        TablaMaterias.setBorder(javax.swing.BorderFactory.createTitledBorder("Materias Inscriptas"));
        TablaMaterias.setForeground(new java.awt.Color(255, 255, 255));
        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Codigo", "Cuatrimetre", "Año", "Condicion", "Asistencia", "Promedio"
            }
        ));
        TablaMaterias.setToolTipText("");
        jScrollPane1.setViewportView(TablaMaterias);

        jScrollPane4.setViewportView(jScrollPane1);

        btnBaja.setText("Dar De Baja");

        btnVolver.setText("Volver al Inicio");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList1);

        Panelinscribir.setBorder(javax.swing.BorderFactory.createTitledBorder("Inscribir Materia"));

        javax.swing.GroupLayout PanelinscribirLayout = new javax.swing.GroupLayout(Panelinscribir);
        Panelinscribir.setLayout(PanelinscribirLayout);
        PanelinscribirLayout.setHorizontalGroup(
            PanelinscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        PanelinscribirLayout.setVerticalGroup(
            PanelinscribirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(27, 58, 107));

        jMenu1.setText("Menu");

        ItemPerfil.setText("Mi Perfil");
        jMenu1.add(ItemPerfil);

        ItemMaterias.setText("Gestion De Materias");
        jMenu1.add(ItemMaterias);

        itemAsistencias.setText("Registrar Asistencia ");
        jMenu1.add(itemAsistencias);

        ItemsCalificacion.setText("Registrar Calificacion ");
        ItemsCalificacion.setToolTipText("");
        jMenu1.add(ItemsCalificacion);

        ItemsAcademicos.setText("Reportes Academicos");
        jMenu1.add(ItemsAcademicos);

        ItemsSalir.setText("Salir");
        jMenu1.add(ItemsSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBaja)
                            .addComponent(btnVolver))
                        .addGap(67, 67, 67)
                        .addComponent(Panelinscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBaja)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVolver))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panelinscribir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Alertas;
    private javax.swing.JMenu ItemMaterias;
    private javax.swing.JMenu ItemPerfil;
    private javax.swing.JMenu ItemsAcademicos;
    private javax.swing.JMenu ItemsCalificacion;
    private javax.swing.JMenu ItemsSalir;
    private javax.swing.JPanel Panelinscribir;
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenu itemAsistencias;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
